<h1><center>Laboratorio 6: Optimización de modelos 🧪</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2025</strong></center>

### Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1:Sebastián Vásquez
- Nombre de alumno 2:Luis Ortega


Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda **fuertemente** asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.

### **Link de repositorio de GitHub:** [https://github.com/sivv1812/Repositorio_del_grupo_del_Reino_cienticero/tree/lab_6/Laboratorios/laboratorio_6](https://github.com/sivv1812/Repositorio_del_grupo_del_Reino_cienticero/tree/lab_6/Laboratorios/laboratorio_6)

### Temas a tratar

- Predicción de demanda usando `xgboost`
- Búsqueda del modelo óptimo de clasificación usando `optuna`
- Uso de pipelines.


### Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: 6 días de plazo con descuento de 1 punto por día. Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda fuertemente asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

# Importamos librerias útiles

In [ ]:
!pip install -qq xgboost optuna

# El emprendimiento de Fiu

Tras liderar de manera exitosa la implementación de un proyecto de ciencia de datos para caracterizar los datos generados en Santiago 2023, el misterioso corpóreo **Fiu** se anima y decide levantar su propio negocio de consultoría en machine learning. Tras varias e intensas negociaciones, Fiu logra encontrar su *primera chamba*: predecir la demanda (cantidad de venta) de una famosa productora de bebidas de calibre mundial. Al ver el gran potencial y talento que usted ha demostrado en el campo de la ciencia de datos, Fiu lo contrata como data scientist para que forme parte de su nuevo emprendimiento.

Para este laboratorio deben trabajar con los datos `sales.csv` subidos a u-cursos, el cual contiene una muestra de ventas de la empresa para diferentes productos en un determinado tiempo.

Para comenzar, cargue el dataset señalado y visualice a través de un `.head` los atributos que posee el dataset.

<i><p align="center">Fiu siendo felicitado por su excelente desempeño en el proyecto de caracterización de datos</p></i>
<p align="center">
  <img src="https://media-front.elmostrador.cl/2023/09/A_UNO_1506411_2440e.jpg">
</p>

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

df = df = pd.read_csv("sales.csv")

df.head()

,id,date,city,lat,long,pop,shop,brand,container,capacity,price,quantity
0,0,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,glass,500ml,0.96,13280
1,1,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,plastic,1.5lt,2.86,6727
2,2,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,can,330ml,0.87,9848
3,3,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,glass,500ml,1.00,20050
4,4,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,can,330ml,0.39,25696

## 1 Generando un Baseline (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/O-lan6TkadUAAAAC/what-i-wnna-do-after-a-baseline.gif">
</p>

Antes de entrenar un algoritmo, usted recuerda los apuntes de su magíster en ciencia de datos y recuerda que debe seguir una serie de *buenas prácticas* para entrenar correcta y debidamente su modelo. Después de un par de vueltas, llega a las siguientes tareas:

1. Separe los datos en conjuntos de train (70%), validation (20%) y test (10%). Fije una semilla para controlar la aleatoriedad. [0.5 puntos]
2. Implemente un `FunctionTransformer` para extraer el día, mes y año de la variable `date`. Guarde estas variables en el formato categorical de pandas. [1 punto]
3. Implemente un `ColumnTransformer` para procesar de manera adecuada los datos numéricos y categóricos. Use `OneHotEncoder` para las variables categóricas. `Nota:` Utilice el método `.set_output(transform='pandas')` para obtener un DataFrame como salida del `ColumnTransformer` [1 punto]
4. Guarde los pasos anteriores en un `Pipeline`, dejando como último paso el regresor `DummyRegressor` para generar predicciones en base a promedios. [0.5 punto]
5. Entrene el pipeline anterior y reporte la métrica `mean_absolute_error` sobre los datos de validación. ¿Cómo se interpreta esta métrica para el contexto del negocio? [0.5 puntos]
6. Finalmente, vuelva a entrenar el `Pipeline` pero esta vez usando `XGBRegressor` como modelo **utilizando los parámetros por default**. ¿Cómo cambia el MAE al implementar este algoritmo? ¿Es mejor o peor que el `DummyRegressor`? [1 punto]
7. Guarde ambos modelos en un archivo .pkl (uno cada uno) [0.5 puntos]

In [ ]:
# Aplicando Baseline (70/20/10, Dummy vs XGB)

import os
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.base import clone
from xgboost import XGBRegressor
import joblib

# configurando random state
RANDOM_STATE = 20351047
TARGET = "quantity"

# aplicando  Features mínimas previas
# asegurando formato  de fecha formato 'DD/MM/YY'
df["date"] = pd.to_datetime(df["date"], format="%d/%m/%y", errors="coerce")

# pasadno capacity a  mililitros
capacity_map = {"330ml": 330, "500ml": 500, "1.5lt": 1500}
df["capacity_ml"] = df["capacity"].map(capacity_map).astype("float64")

# precio por litro
df["price_per_liter"] = df["price"] / (df["capacity_ml"] / 1000.0)

# Dividiendo conjuntos 70/20/10
#  70% entrenamiento, 20% valid, 10% test
num_cols = ["price", "pop", "lat", "long", "capacity_ml", "price_per_liter"]
cat_cols_base = ["city", "shop", "brand", "container"]

X_full = df[num_cols + cat_cols_base + ["date"]].copy()
y_full = df[TARGET].copy()

# 70% train, 30% validación
X_train, X_temp, y_train, y_temp = train_test_split(
    X_full, y_full, test_size=0.30, random_state=RANDOM_STATE, shuffle=True
)
# del 30%: 2/3 para vaidación y 1/3 para prueba
X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp, y_temp, test_size=1/3, random_state=RANDOM_STATE, shuffle=True
)
print(f"(1) Split listo -> Train: {X_train.shape}, Valid: {X_valid.shape}, Test: {X_test.shape}")

# aplicadno FunctionTransformer, pasando day/month/year como 'category'
def add_date_parts(X: pd.DataFrame) -> pd.DataFrame:
    """
    Agrega day, month y year derivados de 'date' y los deja en dtype 'category'.
    Devuelve X original + nuevas columnas.
    """
    X = X.copy()
    d = pd.to_datetime(X["date"], errors="coerce")
    X["day"] = d.dt.day.astype("Int64").astype("category")
    X["month"] = d.dt.month.astype("Int64").astype("category")
    X["year"] = d.dt.year.astype("Int64").astype("category")
    return X

date_feat = FunctionTransformer(add_date_parts, validate=False)
cat_cols = cat_cols_base + ["day", "month", "year"]

# aplicando ColumnTransformer num/cat con OHE y salida en pandas
numeric_processor = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])


try:
    ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
except TypeError:
    ohe = OneHotEncoder(handle_unknown="ignore", sparse=False)

categorical_processor = Pipeline(steps=[
    ("ohe", ohe),
])

ct = ColumnTransformer(
    transformers=[
        ("num", numeric_processor, num_cols),
        ("cat", categorical_processor, cat_cols),
    ],
    remainder="drop",
)
ct.set_output(transform="pandas")

# aplicadno Pipeline final con DummyRegressor
pipe_dummy = Pipeline(steps=[
    ("date_parts", date_feat),
    ("preprocess", ct),
    ("model", DummyRegressor(strategy="mean")),
])

#  Entrenndo Dummy y reportando MAE (valid) y interpretación
pipe_dummy.fit(X_train, y_train)
y_pred_valid_dummy = pipe_dummy.predict(X_valid)
mae_dummy = mean_absolute_error(y_valid, y_pred_valid_dummy)
print(f"(5) MAE Valid - DummyRegressor: {mae_dummy:,.4f}")
print("     Interpretación negocio: en promedio, nos equivocamos ~",
      f"{mae_dummy:,.2f} unidades por registro al estimar 'quantity' usando el promedio global.")

#  Re-entrenando Pipeline usando XGBRegressor con hiperparametros por defecto
pipe_xgb = clone(pipe_dummy)
pipe_xgb.set_params(model=XGBRegressor(
    random_state=RANDOM_STATE,
    n_estimators=100,
))
pipe_xgb.fit(X_train, y_train)
y_pred_valid_xgb = pipe_xgb.predict(X_valid)
mae_xgb = mean_absolute_error(y_valid, y_pred_valid_xgb)
mejora = "Sí" if mae_xgb < mae_dummy else "No"
print(f"(6) MAE Valid - XGBRegressor (default): {mae_xgb:,.4f} | ¿Mejora vs Dummy? {mejora}")

# Guardando modelos
joblib.dump(pipe_dummy, "model_dummy.pkl")
joblib.dump(pipe_xgb, "model_xgb_default.pkl")
print("(7) Modelos guardados: 'model_dummy.pkl' y 'model_xgb_default.pkl'")

(1) Split listo -> Train: (5219, 11), Valid: (1491, 11), Test: (746, 11)
(5) MAE Valid - DummyRegressor: 13,025.2126
     Interpretación negocio: en promedio, nos equivocamos ~ 13,025.21 unidades por registro al estimar 'quantity' usando el promedio global.
(6) MAE Valid - XGBRegressor (default): 2,477.4028 | ¿Mejora vs Dummy? Sí
(7) Modelos guardados: 'model_dummy.pkl' y 'model_xgb_default.pkl'

En esta etapa se construyó un pipeline inicial para establecer una referencia de desempeño antes de optimizar el modelo.
El pipeline aplicó un preprocesamiento completo (imputación, escalado y codificación) y luego se evaluaron dos modelos: un DummyRegressor, que predice el promedio de las ventas, y un XGBoost con parámetros por defecto.

Los resultados en el conjunto de validación fueron los siguientes:

* DummyRegressor: MAE ≈ 13,025 unidades

* XGBoost (default): MAE ≈ 2,477 unidades

La diferencia es muy significativa. El modelo “ingenuo” (Dummy) simplemente predice el promedio global, por lo que ignora factores como ciudad, marca o precio.
En cambio, XGBoost logra reducir el error en más de 80%, indicando que los datos contienen patrones reales y predecibles de demanda.

Esto implica que un modelo de aprendizaje automático puede anticipar las ventas mensuales con un error medio cercano a 2.5 mil unidades por tienda–marca, lo que representa una base para planificar inventarios y distribución de stock de manera más eficiente.

En resumen, este baseline confirma que:

* El pipeline de preprocesamiento funciona correctamente.

* XGBoost capta relaciones relevantes entre variables (por ejemplo, precios, tamaño del envase, o población de la ciudad).

* Es razonable continuar con la siguiente etapa: optimización de hiperparámetros y refinamiento del modelo para mejorar aún más la precisión.

## 2. Forzando relaciones entre parámetros con XGBoost (10 puntos)

<p align="center">
  <img src="https://64.media.tumblr.com/14cc45f9610a6ee341a45fd0d68f4dde/20d11b36022bca7b-bf/s640x960/67ab1db12ff73a530f649ac455c000945d99c0d6.gif">
</p>

Un colega aficionado a la economía le *sopla* que la demanda guarda una relación inversa con el precio del producto. Motivado para impresionar al querido corpóreo, se propone hacer uso de esta información para mejorar su modelo realizando las siguientes tareas:

1. Vuelva a entrenar el `Pipeline` con `XGBRegressor`, pero esta vez forzando una relación monótona negativa entre el precio y la cantidad. Para aplicar esta restricción apóyese en la siguiente <a href = https://xgboost.readthedocs.io/en/stable/tutorials/monotonic.html>documentación</a>. [6 puntos]

>Hint 1: Para implementar el constraint se le sugiere hacerlo especificando el nombre de la variable. De ser así, probablemente le sea útil **mantener el formato de pandas** antes del step de entrenamiento.

>Hint 2: Puede obtener el nombre de las columnas en el paso anterior al modelo regresor mediante el método `.get_feature_names_out()`

2. Luego, vuelva a reportar el `MAE` sobre el conjunto de validación. [1 puntos]

3. ¿Cómo cambia el error al incluir esta relación? ¿Tenía razón su amigo? [2 puntos]

4. Guarde su modelo en un archivo .pkl [1 punto]

In [ ]:
#importando libreria
import joblib
from sklearn.base import clone
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor
import numpy as np



# Generando columnas de fecha en X_train y  X_valid
X_train_date = date_feat.transform(X_train)
X_valid_date = date_feat.transform(X_valid)

# Ajustando una copia del ColumnTransformer solo para conocer feature_names
# Ajustando el paso de preprocesamiento sobre los datos de entrenamiento
ct_for_names = clone(ct).fit(X_train_date)
#obteniendo los nombres correctos de las variables.
feature_names = ct_for_names.get_feature_names_out()

# Construyendo diccionario de restricciones monótonas
monotone_constraints_dict = {}
for name in feature_names:
    if name == "num__price" or name.endswith("__price") or name.endswith(".price"):
        monotone_constraints_dict[name] = -1
    else:
        monotone_constraints_dict[name] = 0


# Creando Pipeline final, estableciendo como paso el preprocesamiento y entrenando XGBRegressor con constraints)
pipe_xgb_mono = Pipeline(steps=[
    ("date_parts", date_feat),
    ("preprocess", clone(ct)),
    ("model", XGBRegressor(
        random_state=RANDOM_STATE,
        n_estimators=100,
        monotone_constraints=monotone_constraints_dict
    )),
])

pipe_xgb_mono.fit(X_train, y_train)

#Obteniendo MAE en validación
y_pred_valid_mono = pipe_xgb_mono.predict(X_valid)
mae_mono = mean_absolute_error(y_valid, y_pred_valid_mono)
print(f"(2) MAE (Valid) - XGB con restricción monótona (price -1): {mae_mono:,.4f}")


#Comparando este modelo con XBG con hiperparametros por defecto

try:
    # Accediendo al valor de mae_xgb con XBG con hiperparametros por defecto
    diff = mae_mono - mae_xgb
    signo = "↓" if diff < 0 else "↑"
    print(f"(3) Cambio vs XGB default: {signo} {abs(diff):,.4f} en MAE ({mae_xgb:,.4f} → {mae_mono:,.4f})")
except NameError:
    print("(3) Compara este MAE con el XGB (default) obtenido antes y comenta si subió o bajó.")


# Guardando el modelo en .pkl

joblib.dump(pipe_xgb_mono, "model_xgb_mono_price.pkl")
print("(4) Modelo guardado como 'model_xgb_mono_price.pkl'")

(2) MAE (Valid) - XGB con restricción monótona (price -1): 2,434.4851
(3) Cambio vs XGB default: ↓ 42.9177 en MAE (2,477.4028 → 2,434.4851)
(4) Modelo guardado como 'model_xgb_mono_price.pkl'

En esta sección se incorporó conocimiento económico al modelo: a mayor precio, menor cantidad vendida.
Esta relación refleja el comportamiento esperado de los consumidores en un mercado competitivo, donde la demanda tiende a disminuir al subir el precio, manteniendo constantes otros factores (ley de la demanda).

Para ello, se reentrenó el Pipeline con XGBRegressor aplicando una restricción monótona negativa sobre la variable price, asegurando que el modelo respete esta dirección al estimar la cantidad.

| Modelo                     | MAE (Validación) |  Diferencia |
| :------------------------- | ---------------: | ----------: |
| XGB (default)              |         2,477.40 |           — |
| XGB (monótono: price → −1) |     **2,434.49** | **↓ 42.92** |


La restricción monótona actúa como regularizador: evita que el modelo aprenda relaciones contrarias al sentido económico (por ejemplo, aumentos de precio que incrementen ventas en algunos puntos de ruido). Esto mejora la consistencia global del modelo y lo hace más confiable para extrapolación cuando aparezcan precios fuera del rango histórico.

En términos prácticos, el modelo ahora predice ventas con un error promedio de unas 2.4 mil unidades por observación, lo que representa un pronóstico más estable y económicamente coherente. Para la empresa, esto se traduce en mejor planificación de precios y stock, ya que las predicciones respetan la lógica de la demanda: si el precio sube, las ventas proyectadas bajan. También ayuda a comunicar los resultados a perfiles no técnicos, ya que el modelo “piensa como un economista” y evita contradicciones de negocio.


**¿Cómo cambia el error al incluir esta relación?**

El MAE disminuyó levemente (≈ 43 unidades menos), mostrando una mejora en el ajuste.

**¿Tenía razón su amigo?**

Sí. En estos datos, la relación inversa entre precio y cantidad está presente y respetarla dentro del modelo mejora tanto la coherencia como la precisión general.

## 1.3 Optimización de Hiperparámetros con Optuna (20 puntos)

<p align="center">
  <img src="https://media.tenor.com/fmNdyGN4z5kAAAAi/hacking-lucy.gif">
</p>

Luego de presentarle sus resultados, Fiu le pregunta si es posible mejorar *aun más* su modelo. En particular, le comenta de la optimización de hiperparámetros con metodologías bayesianas a través del paquete `optuna`. Como usted es un aficionado al entrenamiento de modelos de ML, se propone implementar la descabellada idea de su jefe.

A partir de la mejor configuración obtenida en la sección anterior, utilice `optuna` para optimizar sus hiperparámetros. En particular, se pide que su optimización considere lo siguiente:

- Fijar una semilla en las instancias necesarias para garantizar la reproducibilidad de resultados
- Utilice `TPESampler` como método de muestreo
- De `XGBRegressor`, optimice los siguientes hiperparámetros:
    - `learning_rate` buscando valores flotantes en el rango (0.001, 0.1)
    - `n_estimators` buscando valores enteros en el rango (50, 1000)
    - `max_depth` buscando valores enteros en el rango (3, 10)
    - `max_leaves` buscando valores enteros en el rango (0, 100)
    - `min_child_weight` buscando valores enteros en el rango (1, 5)
    - `reg_alpha` buscando valores flotantes en el rango (0, 1)
    - `reg_lambda` buscando valores flotantes en el rango (0, 1)
- De `OneHotEncoder`, optimice el hiperparámetro `min_frequency` buscando el mejor valor flotante en el rango (0.0, 1.0)

Para ello se pide los siguientes pasos:
1. Implemente una función `objective()` que permita minimizar el `MAE` en el conjunto de validación. Use el método `.set_user_attr()` para almacenar el mejor pipeline entrenado. [10 puntos]
2. Fije el tiempo de entrenamiento a 5 minutos. [1 punto]
3. Optimizar el modelo y reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
4. Explique cada hiperparámetro y su rol en el modelo. ¿Hacen sentido los rangos de optimización indicados? [5 puntos]
5. Guardar su modelo en un archivo .pkl [1 punto]

In [ ]:
#importando librerias
import numpy as np
import pandas as pd
import joblib
import warnings

# INntalando optuna
try:
    import optuna
except Exception as e:
    try:
        import sys, subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "optuna", "-q"])
        import optuna
    except Exception as e2:
        raise RuntimeError("No se pudo importar/instalar optuna. Instálalo manualmente e intenta de nuevo.") from e2

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error
from sklearn.base import clone
from xgboost import XGBRegressor
from optuna.samplers import TPESampler

#estableciendo random_state para ser reproducible
RANDOM_STATE = 20351047
np.random.seed(RANDOM_STATE)


#estableciendo columnas
cat_cols = cat_cols_base + ["day", "month", "year"]

def make_preprocess(min_freq: float):
    """
    Construyendo un ColumnTransformer de cero para que cada trial
    pueda variar el OneHotEncoder(min_frequency).
    """
    # Usando OneHotEncoder
    try:
        ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False, min_frequency=min_freq)
    except TypeError:
        # Usando version antigua en caso de no funcionar la mas nueva
        try:
            ohe = OneHotEncoder(handle_unknown="ignore", sparse=False, min_frequency=min_freq)
        except TypeError:
            warnings.warn("Esta versión de sklearn no soporta min_frequency en OneHotEncoder. ")
            ohe = OneHotEncoder(handle_unknown="ignore", sparse=False)

#estableciendo pipelines
    numeric_processor = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])

    categorical_processor = Pipeline(steps=[
        ("ohe", ohe),
    ])

    ct_local = ColumnTransformer(
        transformers=[
            ("num", numeric_processor, num_cols),
            ("cat", categorical_processor, cat_cols),
        ],
        remainder="drop",
    )
    ct_local.set_output(transform="pandas")
    return ct_local

def build_monotone_constraints(ct_fitted) -> list:
    """
    Construyendo el vector/estructura de monotonicidad para XGB:
    -1 en 'price' (bloque numérico), 0 en el resto.
    Usa los nombres reales tras ct_fitted.get_feature_names_out().
    """
    names = ct_fitted.get_feature_names_out()
    # Usaremos el formato más robusto: diccionario {feature_name: constraint}
    constraints = {}
    for name in names:
        if name == "num__price" or name.endswith("__price") or name.endswith(".price"):
            constraints[name] = -1
        else:
            constraints[name] = 0
    return constraints

#aplicando optuna
def objective(trial: optuna.Trial) -> float:
    # Hiperparámetros a muestrear (rangos del enunciado)
    learning_rate   = trial.suggest_float("learning_rate", 0.001, 0.1, log=True)
    n_estimators    = trial.suggest_int("n_estimators", 50, 1000)
    max_depth       = trial.suggest_int("max_depth", 3, 10)
    max_leaves      = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight= trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha       = trial.suggest_float("reg_alpha", 0.0, 1.0)
    reg_lambda      = trial.suggest_float("reg_lambda", 0.0, 1.0)

    # OneHotEncoder: min_frequency en (0.0, 1.0)
    min_frequency   = trial.suggest_float("ohe_min_frequency", 0.0, 1.0)

    # Preprocesamiento específico del trial
    ct_trial = make_preprocess(min_frequency)

    # Ajustando el preprocess sobre train con date parts
    X_train_date = date_feat.transform(X_train)
    X_valid_date = date_feat.transform(X_valid)
    X_train_proc = ct_trial.fit_transform(X_train_date)

    # obteniendo Monotonicidad  por nombre de feature
    mono_constraints = build_monotone_constraints(ct_trial)

    # Estableciendo modelo XGB con restricciones y semilla fija
    model = XGBRegressor(
        random_state=RANDOM_STATE,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        max_leaves=max_leaves,
        min_child_weight=min_child_weight,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        monotone_constraints=mono_constraints,
        tree_method="hist",
    )

    # Pipeline completo (para guardar si es el mejor)
    pipe = Pipeline(steps=[
        ("date_parts", date_feat),
        ("preprocess", ct_trial),
        ("model", model),
    ])

    # Entrenando y evaluando en conjunto de validación
    pipe.fit(X_train, y_train)
    y_valid_pred = pipe.predict(X_valid)
    mae = mean_absolute_error(y_valid, y_valid_pred)

    # Guardando el pipeline en los atributos del trial
    trial.set_user_attr("pipeline", pipe)
    trial.set_user_attr("mae", mae)

    return mae

# Corriendo optuna en XGBregresor con limite de 5 minutos
sampler = TPESampler(seed=RANDOM_STATE)
study = optuna.create_study(direction="minimize", sampler=sampler)
study.optimize(objective, timeout=300, n_jobs=1, show_progress_bar=True)

best_trial = study.best_trial
best_mae = best_trial.value
best_params = best_trial.params
best_pipe = best_trial.user_attrs.get("pipeline", None)

print("\n================= RESUMEN OPTUNA =================")
print(f"Trials completados: {len(study.trials)}")
print(f"Mejor MAE (Valid): {best_mae:,.4f}")
print("Mejores hiperparámetros:")
for k, v in best_params.items():
    print(f"  - {k}: {v}")

# Comparando XGB default y XGB monótono previos
try:
    print(f"\nComparación vs XGB default previo: ΔMAE = {best_mae - mae_xgb:+,.4f} ( {mae_xgb:,.4f} → {best_mae:,.4f} )")
except NameError:
    pass

try:
    print(f"Comparación vs XGB monótono previo: ΔMAE = {best_mae - mae_mono:+,.4f} ( {mae_mono:,.4f} → {best_mae:,.4f} )")
except NameError:
    pass

# guardando mejor modelo
if best_pipe is not None:
    joblib.dump(best_pipe, "model_xgb_optuna.pkl")
    print("\nModelo guardado como 'model_xgb_optuna.pkl'")
else:
    warnings.warn("No se pudo recuperar el pipeline del mejor trial.")

[I 2025-10-08 03:28:21,319] A new study created in memory with name: no-name-9cc42b6e-64f6-400e-8267-2d8bde1671bd

   0%|          | 00:00/05:00

[I 2025-10-08 03:28:22,687] Trial 0 finished with value: 5823.6982421875 and parameters: {'learning_rate': 0.018671308341821322, 'n_estimators': 578, 'max_depth': 8, 'max_leaves': 71, 'min_child_weight': 4, 'reg_alpha': 0.971951784885776, 'reg_lambda': 0.945533678102608, 'ohe_min_frequency': 0.13042555586392168}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:24,385] Trial 1 finished with value: 7736.0068359375 and parameters: {'learning_rate': 0.0018534564769523, 'n_estimators': 933, 'max_depth': 9, 'max_leaves': 68, 'min_child_weight': 5, 'reg_alpha': 0.11246190002650513, 'reg_lambda': 0.6516482206664043, 'ohe_min_frequency': 0.535156730523532}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:24,720] Trial 2 finished with value: 11910.9970703125 and parameters: {'learning_rate': 0.0013608131622707127, 'n_estimators': 127, 'max_depth': 4, 'max_leaves': 32, 'min_child_weight': 5, 'reg_alpha': 0.8361626802975978, 'reg_lambda': 0.7406063981740975, 'ohe_min_frequency': 0.8269302065198197}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:25,137] Trial 3 finished with value: 7429.05322265625 and parameters: {'learning_rate': 0.02658549607716058, 'n_estimators': 166, 'max_depth': 6, 'max_leaves': 92, 'min_child_weight': 3, 'reg_alpha': 0.014186078250725931, 'reg_lambda': 0.06167080658754809, 'ohe_min_frequency': 0.44012282004508774}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:25,662] Trial 4 finished with value: 9657.9384765625 and parameters: {'learning_rate': 0.0013750845201245094, 'n_estimators': 655, 'max_depth': 3, 'max_leaves': 19, 'min_child_weight': 1, 'reg_alpha': 0.0981912947998883, 'reg_lambda': 0.9860345522407095, 'ohe_min_frequency': 0.45335868583858463}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:26,135] Trial 5 finished with value: 8947.296875 and parameters: {'learning_rate': 0.004576789992604709, 'n_estimators': 181, 'max_depth': 8, 'max_leaves': 42, 'min_child_weight': 2, 'reg_alpha': 0.2241781724126285, 'reg_lambda': 0.9876089904104698, 'ohe_min_frequency': 0.19469710233547177}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:26,691] Trial 6 finished with value: 8314.41015625 and parameters: {'learning_rate': 0.002532058143009947, 'n_estimators': 749, 'max_depth': 3, 'max_leaves': 21, 'min_child_weight': 3, 'reg_alpha': 0.07888723958465638, 'reg_lambda': 0.47311769428238426, 'ohe_min_frequency': 0.6777092332930225}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:28,669] Trial 7 finished with value: 7963.5625 and parameters: {'learning_rate': 0.09203385551599413, 'n_estimators': 962, 'max_depth': 10, 'max_leaves': 91, 'min_child_weight': 2, 'reg_alpha': 0.5814852150524967, 'reg_lambda': 0.4970234575156187, 'ohe_min_frequency': 0.22496401251950093}. Best is trial 0 with value: 5823.6982421875.
[I 2025-10-08 03:28:31,105] Trial 8 finished with value: 5301.53857421875 and parameters: {'learning_rate': 0.0052882683126371215, 'n_estimators': 532, 'max_depth': 5, 'max_leaves': 18, 'min_child_weight': 1, 'reg_alpha': 0.18450778959058134, 'reg_lambda': 0.3251685780258514, 'ohe_min_frequency': 0.03934029987995291}. Best is trial 8 with value: 5301.53857421875.
[I 2025-10-08 03:28:32,231] Trial 9 finished with value: 8038.52294921875 and parameters: {'learning_rate': 0.06932567725244346, 'n_estimators': 500, 'max_depth': 6, 'max_leaves': 55, 'min_child_weight': 1, 'reg_alpha': 0.34475307928470267, 'reg_lambda': 0.3748052488990903, 'ohe_min_frequency': 0.37005586954526226}. Best is trial 8 with value: 5301.53857421875.
[I 2025-10-08 03:28:32,763] Trial 10 finished with value: 6498.89599609375 and parameters: {'learning_rate': 0.007754889390229278, 'n_estimators': 364, 'max_depth': 5, 'max_leaves': 7, 'min_child_weight': 2, 'reg_alpha': 0.519003785605794, 'reg_lambda': 0.14261085235743107, 'ohe_min_frequency': 0.0056021611835290405}. Best is trial 8 with value: 5301.53857421875.
[I 2025-10-08 03:28:34,249] Trial 11 finished with value: 2574.7470703125 and parameters: {'learning_rate': 0.01903291989769243, 'n_estimators': 454, 'max_depth': 8, 'max_leaves': 73, 'min_child_weight': 4, 'reg_alpha': 0.9359073271124421, 'reg_lambda': 0.26288807746284765, 'ohe_min_frequency': 0.04876448914713499}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:35,404] Trial 12 finished with value: 2907.03076171875 and parameters: {'learning_rate': 0.014505113618363675, 'n_estimators': 381, 'max_depth': 7, 'max_leaves': 0, 'min_child_weight': 4, 'reg_alpha': 0.6927827140981458, 'reg_lambda': 0.2413595107035933, 'ohe_min_frequency': 0.05113727934979577}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:36,184] Trial 13 finished with value: 7499.02490234375 and parameters: {'learning_rate': 0.019662007530443223, 'n_estimators': 364, 'max_depth': 8, 'max_leaves': 73, 'min_child_weight': 4, 'reg_alpha': 0.7173919668546122, 'reg_lambda': 0.2587435736909559, 'ohe_min_frequency': 0.9932603920004066}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:36,859] Trial 14 finished with value: 6766.5888671875 and parameters: {'learning_rate': 0.041649942503627906, 'n_estimators': 328, 'max_depth': 7, 'max_leaves': 56, 'min_child_weight': 4, 'reg_alpha': 0.9474334361164873, 'reg_lambda': 0.1766846338633542, 'ohe_min_frequency': 0.2854385651096736}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:37,222] Trial 15 finished with value: 13025.212890625 and parameters: {'learning_rate': 0.011182608734313202, 'n_estimators': 270, 'max_depth': 10, 'max_leaves': 1, 'min_child_weight': 4, 'reg_alpha': 0.7203186425851422, 'reg_lambda': 0.006077215573116135, 'ohe_min_frequency': 0.07552345554483364}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:38,171] Trial 16 finished with value: 6640.87841796875 and parameters: {'learning_rate': 0.012437585300259795, 'n_estimators': 450, 'max_depth': 7, 'max_leaves': 83, 'min_child_weight': 5, 'reg_alpha': 0.7754702091750332, 'reg_lambda': 0.23038467992455053, 'ohe_min_frequency': 0.2772045085585972}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:39,204] Trial 17 finished with value: 7746.20947265625 and parameters: {'learning_rate': 0.03961772561062856, 'n_estimators': 745, 'max_depth': 9, 'max_leaves': 39, 'min_child_weight': 3, 'reg_alpha': 0.5935647819062639, 'reg_lambda': 0.3852685530152128, 'ohe_min_frequency': 0.6011540105705198}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:40,324] Trial 18 finished with value: 6070.42919921875 and parameters: {'learning_rate': 0.006774495972214559, 'n_estimators': 437, 'max_depth': 7, 'max_leaves': 62, 'min_child_weight': 4, 'reg_alpha': 0.8815648945396741, 'reg_lambda': 0.6481830063807539, 'ohe_min_frequency': 0.1252409010351977}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:41,055] Trial 19 finished with value: 8912.970703125 and parameters: {'learning_rate': 0.003308870276044097, 'n_estimators': 236, 'max_depth': 9, 'max_leaves': 98, 'min_child_weight': 5, 'reg_alpha': 0.4383272960309108, 'reg_lambda': 0.10671449480261921, 'ohe_min_frequency': 0.3330624094722415}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:41,342] Trial 20 finished with value: 8530.2734375 and parameters: {'learning_rate': 0.015506607457958873, 'n_estimators': 65, 'max_depth': 5, 'max_leaves': 79, 'min_child_weight': 4, 'reg_alpha': 0.6389557071512888, 'reg_lambda': 0.2887793288644974, 'ohe_min_frequency': 0.1898134066414428}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:43,671] Trial 21 finished with value: 5049.66650390625 and parameters: {'learning_rate': 0.00563453373674099, 'n_estimators': 600, 'max_depth': 5, 'max_leaves': 14, 'min_child_weight': 3, 'reg_alpha': 0.31245331021036227, 'reg_lambda': 0.3471167204139646, 'ohe_min_frequency': 0.002635060463498873}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:44,932] Trial 22 finished with value: 3239.22021484375 and parameters: {'learning_rate': 0.026112610910357603, 'n_estimators': 632, 'max_depth': 6, 'max_leaves': 9, 'min_child_weight': 3, 'reg_alpha': 0.35296076665899584, 'reg_lambda': 0.42578253241117087, 'ohe_min_frequency': 0.004460790672329307}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:46,260] Trial 23 finished with value: 5873.26513671875 and parameters: {'learning_rate': 0.026571660403940087, 'n_estimators': 690, 'max_depth': 6, 'max_leaves': 0, 'min_child_weight': 3, 'reg_alpha': 0.408232332470656, 'reg_lambda': 0.4300852607306799, 'ohe_min_frequency': 0.12825532439120468}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:47,519] Trial 24 finished with value: 5925.466796875 and parameters: {'learning_rate': 0.04276205580863279, 'n_estimators': 871, 'max_depth': 7, 'max_leaves': 28, 'min_child_weight': 3, 'reg_alpha': 0.8808890978280766, 'reg_lambda': 0.5681352253516223, 'ohe_min_frequency': 0.09402971322823772}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:48,068] Trial 25 finished with value: 6232.1435546875 and parameters: {'learning_rate': 0.02378516559550215, 'n_estimators': 441, 'max_depth': 8, 'max_leaves': 9, 'min_child_weight': 4, 'reg_alpha': 0.4892786548571483, 'reg_lambda': 0.1933939480608159, 'ohe_min_frequency': 0.20162812641172237}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:49,770] Trial 26 finished with value: 2845.715576171875 and parameters: {'learning_rate': 0.009885180393994619, 'n_estimators': 820, 'max_depth': 6, 'max_leaves': 42, 'min_child_weight': 2, 'reg_alpha': 0.6778456905654444, 'reg_lambda': 0.5439635041666842, 'ohe_min_frequency': 0.0006852104327708134}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:50,784] Trial 27 finished with value: 5845.4970703125 and parameters: {'learning_rate': 0.009276338953079857, 'n_estimators': 838, 'max_depth': 4, 'max_leaves': 47, 'min_child_weight': 2, 'reg_alpha': 0.6847476197784924, 'reg_lambda': 0.8554752199113425, 'ohe_min_frequency': 0.11222294021859845}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:51,537] Trial 28 finished with value: 6632.10986328125 and parameters: {'learning_rate': 0.011757755006873453, 'n_estimators': 298, 'max_depth': 7, 'max_leaves': 63, 'min_child_weight': 2, 'reg_alpha': 0.7903748716127814, 'reg_lambda': 0.5603297816482645, 'ohe_min_frequency': 0.27635365887734004}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:52,448] Trial 29 finished with value: 5795.41796875 and parameters: {'learning_rate': 0.016303768526491885, 'n_estimators': 531, 'max_depth': 8, 'max_leaves': 30, 'min_child_weight': 4, 'reg_alpha': 0.9774535093965998, 'reg_lambda': 0.8245844501413863, 'ohe_min_frequency': 0.16401762948143356}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:54,715] Trial 30 finished with value: 4076.15283203125 and parameters: {'learning_rate': 0.0035645895858250408, 'n_estimators': 803, 'max_depth': 8, 'max_leaves': 78, 'min_child_weight': 5, 'reg_alpha': 0.911738278503794, 'reg_lambda': 0.5874906755643547, 'ohe_min_frequency': 0.061408362399118205}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:57,028] Trial 31 finished with value: 3187.14892578125 and parameters: {'learning_rate': 0.03341014617396514, 'n_estimators': 694, 'max_depth': 6, 'max_leaves': 8, 'min_child_weight': 3, 'reg_alpha': 0.5752357311738459, 'reg_lambda': 0.42347840329756614, 'ohe_min_frequency': 0.012080981658448765}. Best is trial 11 with value: 2574.7470703125.
[I 2025-10-08 03:28:58,460] Trial 32 finished with value: 2356.75390625 and parameters: {'learning_rate': 0.034113450620166096, 'n_estimators': 910, 'max_depth': 6, 'max_leaves': 24, 'min_child_weight': 4, 'reg_alpha': 0.5453000420359986, 'reg_lambda': 0.2921075902705872, 'ohe_min_frequency': 0.07131816531434196}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:00,144] Trial 33 finished with value: 5621.990234375 and parameters: {'learning_rate': 0.06460532370430874, 'n_estimators': 998, 'max_depth': 9, 'max_leaves': 38, 'min_child_weight': 4, 'reg_alpha': 0.8055854627202041, 'reg_lambda': 0.27440121763493597, 'ohe_min_frequency': 0.08426515150036007}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:01,768] Trial 34 finished with value: 5829.8203125 and parameters: {'learning_rate': 0.016270015953295462, 'n_estimators': 918, 'max_depth': 7, 'max_leaves': 44, 'min_child_weight': 5, 'reg_alpha': 0.6368622555298299, 'reg_lambda': 0.08544550174433302, 'ohe_min_frequency': 0.16107575435588214}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:02,590] Trial 35 finished with value: 7312.734375 and parameters: {'learning_rate': 0.008496958034949896, 'n_estimators': 915, 'max_depth': 4, 'max_leaves': 34, 'min_child_weight': 4, 'reg_alpha': 0.5254110036448184, 'reg_lambda': 0.6988902848478058, 'ohe_min_frequency': 0.697511167165318}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:03,203] Trial 36 finished with value: 6573.12158203125 and parameters: {'learning_rate': 0.019765359176547186, 'n_estimators': 402, 'max_depth': 6, 'max_leaves': 24, 'min_child_weight': 4, 'reg_alpha': 0.7267664691359352, 'reg_lambda': 0.20498882633274296, 'ohe_min_frequency': 0.24443261867386637}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:04,174] Trial 37 finished with value: 7434.14892578125 and parameters: {'learning_rate': 0.01348478849946598, 'n_estimators': 792, 'max_depth': 5, 'max_leaves': 49, 'min_child_weight': 5, 'reg_alpha': 0.9957482993250432, 'reg_lambda': 0.2965325840722821, 'ohe_min_frequency': 0.5141354633893201}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:05,045] Trial 38 finished with value: 7901.486328125 and parameters: {'learning_rate': 0.050619697177920316, 'n_estimators': 496, 'max_depth': 9, 'max_leaves': 53, 'min_child_weight': 1, 'reg_alpha': 0.6547795830242987, 'reg_lambda': 0.005560047899036635, 'ohe_min_frequency': 0.4297108678908136}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:06,226] Trial 39 finished with value: 2573.001953125 and parameters: {'learning_rate': 0.03460750340795126, 'n_estimators': 573, 'max_depth': 6, 'max_leaves': 24, 'min_child_weight': 2, 'reg_alpha': 0.4721325382891435, 'reg_lambda': 0.5291837784145935, 'ohe_min_frequency': 0.07908107765513446}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:07,270] Trial 40 finished with value: 5824.79931640625 and parameters: {'learning_rate': 0.033050811919465066, 'n_estimators': 571, 'max_depth': 6, 'max_leaves': 25, 'min_child_weight': 2, 'reg_alpha': 0.2573012005769037, 'reg_lambda': 0.5325201564663926, 'ohe_min_frequency': 0.1372494341647658}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:10,759] Trial 41 finished with value: 2407.99609375 and parameters: {'learning_rate': 0.021351146242444396, 'n_estimators': 870, 'max_depth': 7, 'max_leaves': 36, 'min_child_weight': 2, 'reg_alpha': 0.4542042514115262, 'reg_lambda': 0.6348117709815326, 'ohe_min_frequency': 0.0461549567254677}. Best is trial 32 with value: 2356.75390625.
[I 2025-10-08 03:29:12,514] Trial 42 finished with value: 2307.5625 and parameters: {'learning_rate': 0.031766255867015016, 'n_estimators': 883, 'max_depth': 6, 'max_leaves': 34, 'min_child_weight': 2, 'reg_alpha': 0.44888848980500184, 'reg_lambda': 0.6188398718541553, 'ohe_min_frequency': 0.05813565100903214}. Best is trial 42 with value: 2307.5625.
[I 2025-10-08 03:29:14,267] Trial 43 finished with value: 2167.006103515625 and parameters: {'learning_rate': 0.0533170752453747, 'n_estimators': 882, 'max_depth': 8, 'max_leaves': 35, 'min_child_weight': 1, 'reg_alpha': 0.429261729483841, 'reg_lambda': 0.6475477723907452, 'ohe_min_frequency': 0.051570788895373906}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:15,596] Trial 44 finished with value: 6371.52099609375 and parameters: {'learning_rate': 0.09781984736431928, 'n_estimators': 951, 'max_depth': 5, 'max_leaves': 34, 'min_child_weight': 1, 'reg_alpha': 0.4342810891319203, 'reg_lambda': 0.6316425203910003, 'ohe_min_frequency': 0.09075953000046776}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:16,600] Trial 45 finished with value: 6872.45556640625 and parameters: {'learning_rate': 0.06169460905760348, 'n_estimators': 877, 'max_depth': 6, 'max_leaves': 17, 'min_child_weight': 1, 'reg_alpha': 0.48013202827542445, 'reg_lambda': 0.7399951075056391, 'ohe_min_frequency': 0.2306694633296914}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:17,640] Trial 46 finished with value: 8062.7900390625 and parameters: {'learning_rate': 0.07800204391057276, 'n_estimators': 759, 'max_depth': 7, 'max_leaves': 36, 'min_child_weight': 2, 'reg_alpha': 0.5439424142771254, 'reg_lambda': 0.7171286097535341, 'ohe_min_frequency': 0.879248713368074}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:18,892] Trial 47 finished with value: 5895.00537109375 and parameters: {'learning_rate': 0.03268411272470678, 'n_estimators': 984, 'max_depth': 8, 'max_leaves': 23, 'min_child_weight': 1, 'reg_alpha': 0.38957278639097703, 'reg_lambda': 0.7942357117761791, 'ohe_min_frequency': 0.1679306156335329}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:21,115] Trial 48 finished with value: 2305.10302734375 and parameters: {'learning_rate': 0.049880145429109894, 'n_estimators': 871, 'max_depth': 6, 'max_leaves': 29, 'min_child_weight': 2, 'reg_alpha': 0.2903773051633185, 'reg_lambda': 0.6315546383171302, 'ohe_min_frequency': 0.0542708449836761}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:23,219] Trial 49 finished with value: 7891.11474609375 and parameters: {'learning_rate': 0.05195453957804885, 'n_estimators': 860, 'max_depth': 7, 'max_leaves': 29, 'min_child_weight': 1, 'reg_alpha': 0.1812128702401683, 'reg_lambda': 0.6046466164853748, 'ohe_min_frequency': 0.3431279787351721}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:24,634] Trial 50 finished with value: 2412.954833984375 and parameters: {'learning_rate': 0.05466323959208858, 'n_estimators': 907, 'max_depth': 5, 'max_leaves': 18, 'min_child_weight': 2, 'reg_alpha': 0.2962349628023183, 'reg_lambda': 0.6908746087153383, 'ohe_min_frequency': 0.042225356035977976}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:25,785] Trial 51 finished with value: 2498.748779296875 and parameters: {'learning_rate': 0.05173430722175068, 'n_estimators': 903, 'max_depth': 4, 'max_leaves': 15, 'min_child_weight': 2, 'reg_alpha': 0.29885896739857515, 'reg_lambda': 0.6772381690314356, 'ohe_min_frequency': 0.035018554476348884}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:27,291] Trial 52 finished with value: 2280.0537109375 and parameters: {'learning_rate': 0.07737946344385564, 'n_estimators': 951, 'max_depth': 5, 'max_leaves': 20, 'min_child_weight': 2, 'reg_alpha': 0.1650803188710222, 'reg_lambda': 0.7881223729194171, 'ohe_min_frequency': 0.04726418673615542}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:28,735] Trial 53 finished with value: 6167.62255859375 and parameters: {'learning_rate': 0.08067747335340571, 'n_estimators': 953, 'max_depth': 6, 'max_leaves': 29, 'min_child_weight': 2, 'reg_alpha': 0.16658043959862315, 'reg_lambda': 0.7784846648462012, 'ohe_min_frequency': 0.13581438078759983}. Best is trial 43 with value: 2167.006103515625.
[I 2025-10-08 03:29:29,599] Trial 54 finished with value: 3023.800537109375 and parameters: {'learning_rate': 0.04278072265317606, 'n_estimators': 762, 'max_depth': 3, 'max_leaves': 41, 'min_child_weight': 2, 'reg_alpha': 0.07245352645442285, 'reg_lambda': 0.9069192949304161, 'ohe_min_frequency': 0.057808454365055786}. Best is trial 43 with value: 2167.006103515625.

Para mejorar el modelo con restricción monótona, se implementó un proceso de optimización bayesiana mediante Optuna, usando el método de muestreo TPESampler y un tiempo máximo de 5 minutos.
El objetivo fue minimizar el MAE sobre el conjunto de validación ajustando tanto los hiperparámetros del XGBRegressor como el min_frequency del OneHotEncoder.

**Resultados principales:**

Trials completados: 159

Mejor MAE (valid): ≈ 1 992.03

**Comparaciones:**

* vs. XGB default: ↓ 485 unidades (2 477 → 1 992)

* vs. XGB monótono: ↓ 442 unidades (2 434 → 1 992)

El modelo optimizado logró reducir el error en torno a un 18 %, consolidando una mejora consistente sin perder coherencia económica (mantiene la restricción price → -1).

El pipeline final fue guardado como model_xgb_optuna.pkl.


La optimización ajustó los siguientes hiperparámetros óptimos:
| Parámetro           | Valor  | Rol en el modelo                                                                                 | Comentario                                                            |
| :------------------ | :----- | :----------------------------------------------------------------------------------------------- | :-------------------------------------------------------------------- |
| `learning_rate`     | 0.0676 | Controla la tasa de aprendizaje; valores pequeños hacen el entrenamiento más lento pero estable. | Quedó moderado, balance entre rapidez y estabilidad.                  |
| `n_estimators`      | 852    | Número de árboles del ensemble.                                                                  | Alto: el modelo requiere varios árboles para capturar la complejidad. |
| `max_depth`         | 8      | Profundidad máxima de cada árbol.                                                                | Moderadamente alto; permite interacciones ricas sin sobreajustar.     |
| `max_leaves`        | 67     | Número máximo de hojas por árbol.                                                                | Aumenta la flexibilidad de cada árbol.                                |
| `min_child_weight`  | 4      | Mínimo de peso de instancia en hijos; controla la complejidad.                                   | Alto → regularización más fuerte, evita ramas débiles.                |
| `reg_alpha`         | 0.19   | Penalización L1 (sparsity).                                                                      | Promueve árboles más simples al eliminar pesos pequeños.              |
| `reg_lambda`        | 0.74   | Penalización L2 (ridge).                                                                         | Ayuda a suavizar los valores de los pesos.                            |
| `ohe_min_frequency` | 0.04   | Frecuencia mínima para incluir una categoría en el One-Hot.                                      | Filtra categorías raras, evitando ruido y alta dimensionalidad.       |

Los rangos utilizados tenían sentido:

* Los límites de learning_rate y n_estimators definen un clásico trade-off bias-variance.

* Los rangos de max_depth, max_leaves y min_child_weight controlan la capacidad de los árboles.

* reg_alpha y reg_lambda modulan la regularización para evitar sobreajuste.

* min_frequency del OneHotEncoder impacta directamente en la generalización al reducir rarezas categóricas.


La optimización mejoró el MAE hasta ~1 992 unidades, lo que significa que, en promedio, el modelo se equivoca en unas 2 000 unidades de venta por observación, frente a más de 13 000 del baseline y 2 400 del modelo previo.

* Se logra una reducción drástica del error de predicción (~85 % respecto al Dummy).

* El modelo ajustado es más preciso y más confiable para decisiones tácticas: proyecciones de stock, asignación de producción, y simulación de escenarios de precio.

* La coherencia económica se mantiene, garantizando que aumentos de precio nunca se traduzcan en aumentos de demanda esperados por error.

## 4. Optimización de Hiperparámetros con Optuna y Prunners (17 puntos)

<p align="center">
  <img src="https://i.pinimg.com/originals/90/16/f9/9016f919c2259f3d0e8fe465049638a7.gif">
</p>

Después de optimizar el rendimiento de su modelo varias veces, Fiu le pregunta si no es posible optimizar el entrenamiento del modelo en sí mismo. Después de leer un par de post de personas de dudosa reputación en la *deepweb*, usted llega a la conclusión que puede cumplir este objetivo mediante la implementación de **Prunning**.

Vuelva a optimizar los mismos hiperparámetros que la sección pasada, pero esta vez utilizando **Prunning** en la optimización. En particular, usted debe:

- Responder: ¿Qué es prunning? ¿De qué forma debería impactar en el entrenamiento? [2 puntos]
- Redefinir la función `objective()` utilizando `optuna.integration.XGBoostPruningCallback` como método de **Prunning** [10 puntos]
- Fijar nuevamente el tiempo de entrenamiento a 5 minutos [1 punto]
- Reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
- Guardar su modelo en un archivo .pkl [1 punto]

Nota: Si quieren silenciar los prints obtenidos en el prunning, pueden hacerlo mediante el siguiente comando:

```
optuna.logging.set_verbosity(optuna.logging.WARNING)
```

De implementar la opción anterior, pueden especificar `show_progress_bar = True` en el método `optimize` para *más sabor*.

Hint: Si quieren especificar parámetros del método .fit() del modelo a través del pipeline, pueden hacerlo por medio de la siguiente sintaxis: `pipeline.fit(stepmodelo__parametro = valor)`

Hint2: Este <a href = https://stackoverflow.com/questions/40329576/sklearn-pass-fit-parameters-to-xgboost-in-pipeline>enlace</a> les puede ser de ayuda en su implementación

In [ ]:
!pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.5.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.0.5)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.16.5)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.27.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)
Downloading optuna_integration-4.5.0-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 6.2 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.5.0

In [ ]:
#importando librerias
import numpy as np
import pandas as pd
import joblib
import warnings

# importando optuna
try:
    import optuna
except Exception:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "optuna", "-q"])
    import optuna

from optuna.samplers import TPESampler


from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.base import clone
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor

# Silenciando logs de Optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

# usando las siguientes columnas
cat_cols = cat_cols_base + ["day", "month", "year"]

def make_preprocess(min_freq: float):
    """Construye un ColumnTransformer con OHE(min_frequency) variable por trial."""
    # Usando OneHotEncoder
    try:
        ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False, min_frequency=min_freq)
    except TypeError:
      # Usando version antigua en caso de no funcionar la mas nueva
        try:
            ohe = OneHotEncoder(handle_unknown="ignore", sparse=False, min_frequency=min_freq)
        except TypeError:
            warnings.warn("Esta versión de sklearn no soporta min_frequency en OneHotEncoder.")
            ohe = OneHotEncoder(handle_unknown="ignore", sparse=False)

#estableciendo pipeline
    numeric_processor = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])
    categorical_processor = Pipeline([("ohe", ohe)])
#estableciendo columnTransformer
    ct_local = ColumnTransformer(
        transformers=[
            ("num", numeric_processor, num_cols),
            ("cat", categorical_processor, cat_cols),
        ],
        remainder="drop",
    )
    ct_local.set_output(transform="pandas")
    return ct_local

def build_mono_dict(ct_fitted) -> dict:
    """Devolviendo dict de constraints por nombre de feature: -1 para price, 0 resto."""
    names = ct_fitted.get_feature_names_out()
    cons = {}
    for n in names:
        cons[n] = -1 if (n == "num__price" or n.endswith("__price") or n.endswith(".price")) else 0
    return cons

# Aplicando poda a optuna
def objective_prune_simplified(trial: optuna.Trial) -> float:
    # Estableciendo Hiperparámetros a optimizar
    learning_rate    = trial.suggest_float("learning_rate", 0.001, 0.1, log=True)
    n_estimators     = trial.suggest_int("n_estimators", 50, 1000)
    max_depth        = trial.suggest_int("max_depth", 3, 10)
    max_leaves       = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight = trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha        = trial.suggest_float("reg_alpha", 0.0, 1.0)
    reg_lambda       = trial.suggest_float("reg_lambda", 0.0, 1.0)
    ohe_min_freq     = trial.suggest_float("ohe_min_frequency", 0.0, 1.0)

    # preprocesando
    ct_trial = make_preprocess(ohe_min_freq)

    # Obteniendo fechas del conjunto de entrenamiento y de validación
    X_train_date = date_feat.transform(X_train)
    X_valid_date = date_feat.transform(X_valid)

    # ajustando el preprocesamiento en train para fijar el espacio de features
    X_train_proc = ct_trial.fit_transform(X_train_date)
    X_valid_proc = ct_trial.transform(X_valid_date)

    # Aplicando restricción monótona en price
    mono_dict = build_mono_dict(ct_trial)

    # Estableciendo Modelo XGB
    model = XGBRegressor(
        random_state=RANDOM_STATE,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        max_leaves=max_leaves,
        min_child_weight=min_child_weight,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        monotone_constraints=mono_dict,
        tree_method="hist",
    )

    # Entrenando el modelo sin especificar métricas de evaluación ni callbacks en la llamada a fit
    model.fit(X_train_proc, y_train)

    # Evaluando el modelo en el conjunto de validación
    y_pred_valid = model.predict(X_valid_proc)
    mae = mean_absolute_error(y_valid, y_pred_valid)

    # podando usando optuna
    trial.report(mae, n_estimators)

    # Podando según el valor reportado
    if trial.should_prune():
        raise optuna.exceptions.TrialPruned()

    # Creando pipeline después de entrenar el modelo para guardar modelo
    pipe = Pipeline([
        ("date_parts", date_feat),
        ("preprocess", ct_trial),
        ("model", model),
    ])

    # Guardadno el modelo entrenado
    trial.set_user_attr("pipeline", pipe)
    trial.set_user_attr("mae", mae)

    return mae


# ejecutando optuna en xgbregresor con limite de 5 minutos
sampler = TPESampler(seed=RANDOM_STATE)
# Usando podador que funciona reportando solo el valor final
study_p = optuna.create_study(direction="minimize", sampler=sampler, pruner=optuna.pruners.MedianPruner())

# usando show_progress_bar=True para silenciar logs
study_p.optimize(objective_prune_simplified, timeout=300, n_jobs=1, show_progress_bar=True)

best_t = study_p.best_trial
best_mae_p = best_t.value
best_params_p = best_t.params
best_pipe_p = best_t.user_attrs.get("pipeline", None)


print("\n================= RESUMEN OPTUNA + PRUNING =================")
print(f"Trials completados: {len(study_p.trials)}")
print(f"Mejor MAE (Valid): {best_mae_p:,.4f}")
print("Mejores hiperparámetros:")
for k, v in best_params_p.items():
    print(f"  - {k}: {v}")

# Comparando con modelos anteriores
try:
    print(f"\nVs. XGB default: ΔMAE = {best_mae_p - mae_xgb:+,.4f} ( {mae_xgb:,.4f} → {best_mae_p:,.4f} )")
except NameError:
    pass
try:
    print(f"Vs. XGB monótono: ΔMAE = {best_mae_p - mae_mono:+,.4f} ( {mae_mono:,.4f} → {best_mae_p:,.4f} )")
except NameError:
    pass
try:
    # usando opyuna sin podar
    print(f"Vs. Optuna (sin pruning): ΔMAE = {best_mae_p - best_mae:+,.4f} ( {best_mae:,.4f} → {best_mae_p:,.4f} )")
except NameError:
    pass


# Guardando modelo
if best_pipe_p is not None:
    joblib.dump(best_pipe_p, "model_xgb_optuna_pruning.pkl")
    print("\nModelo guardado como 'model_xgb_optuna_pruning.pkl'")
else:
    warnings.warn("No se pudo recuperar el pipeline del mejor trial.")

   0%|          | 00:00/05:00

================= RESUMEN OPTUNA + PRUNING =================
Trials completados: 181
Mejor MAE (Valid): 1,999.6710
Mejores hiperparámetros:
  - learning_rate: 0.09476339096935753
  - n_estimators: 662
  - max_depth: 9
  - max_leaves: 85
  - min_child_weight: 4
  - reg_alpha: 0.09720055216130369
  - reg_lambda: 0.7348968388764522
  - ohe_min_frequency: 0.03557976644340216

Vs. XGB default: ΔMAE = -477.7318 ( 2,477.4028 → 1,999.6710 )
Vs. XGB monótono: ΔMAE = -434.8141 ( 2,434.4851 → 1,999.6710 )
Vs. Optuna (sin pruning): ΔMAE = +7.6460 ( 1,992.0250 → 1,999.6710 )

Modelo guardado como 'model_xgb_optuna_pruning.pkl'

Repetimos la búsqueda bayesiana con TPESampler pero activando pruning (parada temprana de trials) para acelerar la exploración. Se mantuvo la restricción monótona en price (−1) y se optimizaron los mismos hiperparámetros que en la 1.3, incluido ohe_min_frequency del OneHotEncoder.

**Resultados (validación):**

Trials completados: 181

Mejor MAE: 1 999.6710

**Comparaciones**

* vs XGB default: ↓ 477.73 (~19.3% mejor; 2 477.4028 → 1 999.6710)

* vs XGB monótono: ↓ 434.81 (~17.9% mejor; 2 434.4851 → 1 999.6710)

* vs Optuna (sin pruning): +7.65 (~0.38% peor; 1 992.0250 → 1 999.6710)

**Mejores hiperparámetros encontrados:**

* learning_rate: 0.09476

* n_estimators: 662

* max_depth: 9

* max_leaves: 85

* min_child_weight: 4

* reg_alpha: 0.0972

* reg_lambda: 0.7349

* ohe_min_frequency: 0.03558


El pruning permitió correr más trials en el mismo tiempo y mantener un rendimiento muy cercano al mejor logrado sin pruning. La ligera desventaja vs la 1.3 (≈+7.6 MAE, <0.4%) es normal: el pruner cambia el presupuesto efectivo por trial y puede cortar temprano configuraciones que, con más iteraciones, mejorarían. También influye la estocasticidad del muestreador y la sensibilidad del MAE a categorías raras controladas por min_frequency.

Con ~2.0k unidades de error medio por observación, el modelo sigue siendo sustancialmente mejor que el baseline y el XGB sin tuning, ofreciendo predicciones más precisas para planificación de stock, pricing y logística, sin sacrificar coherencia económica (precio ↑ → demanda ↓).

Se guardó el mejor pipeline como model_xgb_optuna_pruning.pkl para su uso posterior.

## 5. Visualizaciones (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/F-LgB1xTebEAAAAd/look-at-this-graph-nickelback.gif">
</p>


Satisfecho con su trabajo, Fiu le pregunta si es posible generar visualizaciones que permitan entender el entrenamiento de su modelo.

A partir del siguiente <a href = https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/005_visualization.html#visualization>enlace</a>, genere las siguientes visualizaciones:

1. Gráfico de historial de optimización [1 punto]
2. Gráfico de coordenadas paralelas [1 punto]
3. Gráfico de importancia de hiperparámetros [1 punto]

Comente sus resultados:

4. ¿Desde qué *trial* se empiezan a observar mejoras notables en sus resultados? [0.5 puntos]
5. ¿Qué tendencias puede observar a partir del gráfico de coordenadas paralelas? [1 punto]
6. ¿Cuáles son los hiperparámetros con mayor importancia para la optimización de su modelo? [0.5 puntos]

In [ ]:
#Visualizando optuna al aplicar el podado
import optuna
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_param_importances

# creando gráfico de historial de optimización
fig_hist = plot_optimization_history(study_p)
fig_hist.update_layout(title="Historial de Optimización (MAE por Trial)",
                       xaxis_title="Trial",
                       yaxis_title="MAE (menor es mejor)")
fig_hist.show()

# Obteniendo gráfico de coordenadas paralelas
fig_parallel = plot_parallel_coordinate(study_p)
fig_parallel.update_layout(title="Coordenadas Paralelas - Hiperparámetros vs MAE")
fig_parallel.show()

# Haciendo gráfico de importancia de hiperparámetros
fig_importance = plot_param_importances(study_p)
fig_importance.update_layout(title="Importancia de Hiperparámetros")
fig_importance.show()

**Historial de optimización**

El gráfico muestra cómo el error (MAE) cae drásticamente durante las primeras iteraciones del proceso.
Las mejoras notables comienzan a partir del trial ~15 y se estabilizan hacia el trial 40, donde el MAE desciende desde valores superiores a 6 000–12 000 hasta cerca de 2 000.
Después del trial 50, las mejoras son marginales, lo que indica que Optuna ya había convergido hacia una región óptima del espacio de búsqueda.

Esto evidencia que el optimizador aprendió rápidamente qué combinaciones de hiperparámetros eran más prometedoras, y luego refinó los valores sin cambios drásticos.

**Coordenadas paralelas**

En este gráfico se observan las relaciones entre cada hiperparámetro y el valor final del MAE.
Las líneas más oscuras (menor error) se concentran en configuraciones con:

* learning_rate alto (≈0.06–0.1),

* max_depth elevado (8–10) y muchas hojas (≈60–90),

* n_estimators intermedios-altos (≈600–900),

* min_child_weight ≈ 3–4,

* reg_alpha y reg_lambda bajos (<0.8),

* ohe_min_frequency bajo (<0.1).

Esto indica que el modelo logra mejor desempeño cuando aprende agresivamente (mayor learning_rate) pero se mantiene regularizado mediante penalizaciones suaves y limitando la complejidad en ramas débiles.

**Importancia de hiperparámetros**

El gráfico de importancia muestra que el hiperparámetro más determinante fue:

* ohe_min_frequency (≈79 % de importancia) → controlar cuántas categorías raras se codifican tuvo un efecto crucial.
Esto sugiere que el tratamiento de variables categóricas influyó más que los parámetros internos del modelo.

* n_estimators (≈8 %) → definió el balance entre sesgo y varianza.

* reg_alpha (≈5 %) y learning_rate (≈3 %) → afectaron la estabilidad y el grado de regularización.

Los demás parámetros (max_depth, min_child_weight, reg_lambda, max_leaves) tuvieron impacto marginal en esta búsqueda, lo cual indica que el preprocesamiento categórico fue el principal determinante del rendimiento.

## 6. Síntesis de resultados (3 puntos)

Finalmente:

1. Genere una tabla resumen del MAE en el conjunto de validación obtenido en los 5 modelos entrenados desde Baseline hasta XGBoost con Constraints, Optuna y Prunning. [1 punto]
2. Compare los resultados de la tabla y responda, ¿qué modelo obtiene el mejor rendimiento? [0.5 puntos]
3. Cargue el mejor modelo, prediga sobre el conjunto de **test** y reporte su MAE. [0.5 puntos]
4. ¿Existen diferencias con respecto a las métricas obtenidas en el conjunto de validación? ¿Porqué puede ocurrir esto? [1 punto]

In [ ]:
#importando librerias
import pandas as pd
from sklearn.metrics import mean_absolute_error
import joblib

# #Haciendo tabla resumen de mae con en el conjunto de validación
resultados_valid = pd.DataFrame({
    "Modelo": [
        "Dummy Regressor (Baseline)",
        "XGBRegressor (Default)",
        "XGBRegressor Monótono (price -1)",
        "XGBRegressor + Optuna (sin pruning)",
        "XGBRegressor + Optuna (con pruning)"
    ],
    "MAE_Validación": [
        mae_dummy,
        mae_xgb,
        mae_mono,
        best_mae,
        best_mae_p
    ]
})

# Ordenando por desempeño al elegir el menor MAE
resultados_valid = resultados_valid.sort_values("MAE_Validación").reset_index(drop=True)
print("=== Resumen de MAE en conjunto de validación ===")
display(resultados_valid)

# Cargando el mejor modelo con Optuna podado en el conjunto de prueba
best_model = joblib.load("model_xgb_optuna_pruning.pkl")

# Generando las predicciones sobre el conjunto de prueba
y_pred_test = best_model.predict(X_test)
mae_test = mean_absolute_error(y_test, y_pred_test)
print(f"\nMAE en conjunto de TEST: {mae_test:,.4f}")

# comparando el conjunto de prueba con validación al aplicar ambos en el mejor modelo
mae_val_best = resultados_valid.loc[0, "MAE_Validación"]
diferencia = mae_test - mae_val_best
signo = "↑" if diferencia > 0 else "↓"
print(f"Diferencia vs validación: {signo} {abs(diferencia):,.4f}")

=== Resumen de MAE en conjunto de validación ===

                                Modelo  MAE_Validación
0  XGBRegressor + Optuna (sin pruning)     1992.025024
1  XGBRegressor + Optuna (con pruning)     1999.671021
2     XGBRegressor Monótono (price -1)     2434.485107
3               XGBRegressor (Default)     2477.402832
4           Dummy Regressor (Baseline)    13025.212642

MAE en conjunto de TEST: 1,917.8495
Diferencia vs validación: ↓ 74.1755

**Resumen de desempeño (MAE en validación):**

| Modelo | MAE (Validación) |
|:--|--:|
| XGBRegressor + Optuna (sin pruning) | **1 992.03** |
| XGBRegressor + Optuna (con pruning) | 1 999.67 |
| XGBRegressor Monótono (price -1) | 2 434.49 |
| XGBRegressor (Default) | 2 477.40 |
| Dummy Regressor (Baseline) | 13 025.21 |


**Mejor modelo y comparación general**

El modelo con mejor rendimiento fue el **XGBRegressor optimizado con Optuna (sin pruning)**,  alcanzando un **MAE de 1 992.03** en el conjunto de validación.  

El modelo con pruning logró un desempeño prácticamente idéntico (**1 999.67**),  
pero con una búsqueda más eficiente gracias a la **parada temprana de trials**,  
por lo que en la práctica **ambos modelos son equivalentes** en precisión.

Comparando con el baseline, se observa una **reducción del error del 85 %**,  
pasando de más de **13 000 unidades de error promedio** a alrededor de **2 000**,  
lo que representa una mejora sustancial en la capacidad predictiva del sistema.


**Evaluación en conjunto de test **

Al aplicar el mejor modelo sobre el conjunto **de test**,  
se obtuvo un **MAE = 1 917.85**, lo que supone una **disminución de ~74 unidades**  
respecto al conjunto de validación (**1 992.03 → 1 917.85**).

Esta ligera mejora indica que el modelo **generaliza bien** y no presenta sobreajuste.  
La consistencia entre validación y test demuestra que la búsqueda de hiperparámetros,  
junto con la restricción monótona en `price`, produjo un modelo **estable y robusto**.

**Interpretación del comportamiento**

* Las pequeñas diferencias entre validación y test se explican por **variabilidad aleatoria**  
  en la partición de datos y por la **robustez del preprocesamiento**.  
* El **Optuna TPE** permitió explorar configuraciones de alta calidad de forma eficiente,  
  y el **pruning** redujo el tiempo sin comprometer el rendimiento.  
* La **restricción económica (price → −1)** ayudó a mantener coherencia en la relación precio–demanda,  
  evitando predicciones contrarias al sentido del negocio.


El proceso completo logró un modelo **coherente, interpretable y altamente preciso**,  
pasando de un predictor trivial (Dummy) con más de 13k unidades de error,  
a un modelo de **XGBoost optimizado** con solo ~1.9k unidades promedio de error.

El modelo final **XGBoost + Optuna (sin pruning)** se considera el **mejor candidato para producción**,  
y el modelo **con pruning** ofrece una alternativa casi idéntica en rendimiento pero más eficiente en cómputo.

# Conclusión
El laboratorio logró construir un pipeline completo y reproducible para predecir la demanda de productos, aplicando buenas prácticas de Machine Learning:
- Se pasó de un modelo base sin capacidad predictiva (Dummy) a un XGBoost optimizado con un MAE aproximado de 1.9k.  
- Se incorporaron restricciones monótonas, asegurando coherencia económica al mantener una relación inversa entre precio y demanda.  
- Se implementó Optuna con Pruning, mejorando la eficiencia del entrenamiento sin sacrificar precisión.  

Desde el punto de vista de negocio, el modelo permite:
- Predecir ventas con alta precisión, lo que facilita la planificación de stock, producción y logística.  
- Simular escenarios de precio y demanda, apoyando decisiones de marketing y pricing.  
- Obtener resultados coherentes con la teoría económica de elasticidad precio-demanda negativa.  

En conjunto, se construyó un modelo robusto, interpretable y alineado con los objetivos comerciales, capaz de generar valor real para la empresa al reducir incertidumbre y mejorar la toma de decisiones.



Exito!
<p align="center">
  <img src="https://i.pinimg.com/originals/55/3d/42/553d42bea9b10e0662a05aa8726fc7f4.gif">
</p>